// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: disease_metrics.sql

package repo

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const CountDiseaseMetrics = `-- name: CountDiseaseMetrics :one
SELECT COUNT(*) FROM disease_metrics
`

func (q *Queries) CountDiseaseMetrics(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountDiseaseMetrics)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateDiseaseMetric = `-- name: CreateDiseaseMetric :exec
INSERT INTO disease_metrics (
    disease_id,
    metric_id,
    name,
    enum_name,
    created_at
) VALUES ($1, $2, $3, $4, $5)
`

type CreateDiseaseMetricParams struct {
	DiseaseID uuid.UUID `db:"disease_id"`
	MetricID  uuid.UUID `db:"metric_id"`
	Name      string    `db:"name"`
	EnumName  string    `db:"enum_name"`
	CreatedAt time.Time `db:"created_at"`
}

// SQL constants for mutations (used in repository)
func (q *Queries) CreateDiseaseMetric(ctx context.Context, arg CreateDiseaseMetricParams) error {
	_, err := q.db.ExecContext(ctx, CreateDiseaseMetric,
		arg.DiseaseID,
		arg.MetricID,
		arg.Name,
		arg.EnumName,
		arg.CreatedAt,
	)
	return err
}

const DeleteDiseaseMetric = `-- name: DeleteDiseaseMetric :exec
DELETE FROM disease_metrics
WHERE disease_id = $1 AND metric_id = $2
`

type DeleteDiseaseMetricParams struct {
	DiseaseID uuid.UUID `db:"disease_id"`
	MetricID  uuid.UUID `db:"metric_id"`
}

func (q *Queries) DeleteDiseaseMetric(ctx context.Context, arg DeleteDiseaseMetricParams) error {
	_, err := q.db.ExecContext(ctx, DeleteDiseaseMetric, arg.DiseaseID, arg.MetricID)
	return err
}

const GetDiseaseMetric = `-- name: GetDiseaseMetric :one
SELECT disease_id, metric_id, name, enum_name, updated_at, created_at
FROM disease_metrics
WHERE disease_id = $1 AND metric_id = $2
LIMIT 1
`

type GetDiseaseMetricParams struct {
	DiseaseID uuid.UUID `db:"disease_id"`
	MetricID  uuid.UUID `db:"metric_id"`
}

type GetDiseaseMetricRow struct {
	DiseaseID uuid.UUID    `db:"disease_id"`
	MetricID  uuid.UUID    `db:"metric_id"`
	Name      string       `db:"name"`
	EnumName  string       `db:"enum_name"`
	UpdatedAt sql.NullTime `db:"updated_at"`
	CreatedAt time.Time    `db:"created_at"`
}

func (q *Queries) GetDiseaseMetric(ctx context.Context, arg GetDiseaseMetricParams) (GetDiseaseMetricRow, error) {
	row := q.db.QueryRowContext(ctx, GetDiseaseMetric, arg.DiseaseID, arg.MetricID)
	var i GetDiseaseMetricRow
	err := row.Scan(
		&i.DiseaseID,
		&i.MetricID,
		&i.Name,
		&i.EnumName,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const ListDiseaseMetrics = `-- name: ListDiseaseMetrics :many
SELECT disease_id, metric_id, name, enum_name, updated_at, created_at
FROM disease_metrics
ORDER BY disease_id, name
`

type ListDiseaseMetricsRow struct {
	DiseaseID uuid.UUID    `db:"disease_id"`
	MetricID  uuid.UUID    `db:"metric_id"`
	Name      string       `db:"name"`
	EnumName  string       `db:"enum_name"`
	UpdatedAt sql.NullTime `db:"updated_at"`
	CreatedAt time.Time    `db:"created_at"`
}

func (q *Queries) ListDiseaseMetrics(ctx context.Context) ([]ListDiseaseMetricsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListDiseaseMetrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDiseaseMetricsRow{}
	for rows.Next() {
		var i ListDiseaseMetricsRow
		if err := rows.Scan(
			&i.DiseaseID,
			&i.MetricID,
			&i.Name,
			&i.EnumName,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListDiseaseMetricsByDiseaseID = `-- name: ListDiseaseMetricsByDiseaseID :many
SELECT disease_id, metric_id, name, enum_name, updated_at, created_at
FROM disease_metrics
WHERE disease_id = $1
ORDER BY name
`

type ListDiseaseMetricsByDiseaseIDRow struct {
	DiseaseID uuid.UUID    `db:"disease_id"`
	MetricID  uuid.UUID    `db:"metric_id"`
	Name      string       `db:"name"`
	EnumName  string       `db:"enum_name"`
	UpdatedAt sql.NullTime `db:"updated_at"`
	CreatedAt time.Time    `db:"created_at"`
}

func (q *Queries) ListDiseaseMetricsByDiseaseID(ctx context.Context, diseaseID uuid.UUID) ([]ListDiseaseMetricsByDiseaseIDRow, error) {
	rows, err := q.db.QueryContext(ctx, ListDiseaseMetricsByDiseaseID, diseaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDiseaseMetricsByDiseaseIDRow{}
	for rows.Next() {
		var i ListDiseaseMetricsByDiseaseIDRow
		if err := rows.Scan(
			&i.DiseaseID,
			&i.MetricID,
			&i.Name,
			&i.EnumName,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateDiseaseMetric = `-- name: UpdateDiseaseMetric :exec
UPDATE disease_metrics
SET
    name = $3,
    enum_name = $4,
    updated_at = $5
WHERE disease_id = $1 AND metric_id = $2
`

type UpdateDiseaseMetricParams struct {
	DiseaseID uuid.UUID    `db:"disease_id"`
	MetricID  uuid.UUID    `db:"metric_id"`
	Name      string       `db:"name"`
	EnumName  string       `db:"enum_name"`
	UpdatedAt sql.NullTime `db:"updated_at"`
}

func (q *Queries) UpdateDiseaseMetric(ctx context.Context, arg UpdateDiseaseMetricParams) error {
	_, err := q.db.ExecContext(ctx, UpdateDiseaseMetric,
		arg.DiseaseID,
		arg.MetricID,
		arg.Name,
		arg.EnumName,
		arg.UpdatedAt,
	)
	return err
}
