// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: diseases.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const CountDiseases = `-- name: CountDiseases :one
SELECT COUNT(*) FROM diseases
`

func (q *Queries) CountDiseases(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountDiseases)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateDisease = `-- name: CreateDisease :exec
INSERT INTO diseases (
    disease_id,
    name,
    code,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5)
`

type CreateDiseaseParams struct {
	DiseaseID uuid.UUID `db:"disease_id"`
	Name      string    `db:"name"`
	Code      string    `db:"code"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

// SQL constants for mutations (used in repository)
func (q *Queries) CreateDisease(ctx context.Context, arg CreateDiseaseParams) error {
	_, err := q.db.ExecContext(ctx, CreateDisease,
		arg.DiseaseID,
		arg.Name,
		arg.Code,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const DeleteDisease = `-- name: DeleteDisease :exec
DELETE FROM diseases
WHERE disease_id = $1
`

func (q *Queries) DeleteDisease(ctx context.Context, diseaseID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, DeleteDisease, diseaseID)
	return err
}

const GetDisease = `-- name: GetDisease :one
SELECT disease_id, name, code, created_at, updated_at
FROM diseases
WHERE disease_id = $1
LIMIT 1
`

func (q *Queries) GetDisease(ctx context.Context, diseaseID uuid.UUID) (Disease, error) {
	row := q.db.QueryRowContext(ctx, GetDisease, diseaseID)
	var i Disease
	err := row.Scan(
		&i.DiseaseID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetDiseaseByCode = `-- name: GetDiseaseByCode :one
SELECT disease_id, name, code, created_at, updated_at
FROM diseases
WHERE code = $1
LIMIT 1
`

func (q *Queries) GetDiseaseByCode(ctx context.Context, code string) (Disease, error) {
	row := q.db.QueryRowContext(ctx, GetDiseaseByCode, code)
	var i Disease
	err := row.Scan(
		&i.DiseaseID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListDiseases = `-- name: ListDiseases :many
SELECT disease_id, name, code, created_at, updated_at
FROM diseases
ORDER BY name ASC
`

func (q *Queries) ListDiseases(ctx context.Context) ([]Disease, error) {
	rows, err := q.db.QueryContext(ctx, ListDiseases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Disease{}
	for rows.Next() {
		var i Disease
		if err := rows.Scan(
			&i.DiseaseID,
			&i.Name,
			&i.Code,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateDisease = `-- name: UpdateDisease :exec
UPDATE diseases
SET
    name = $2,
    code = $3,
    updated_at = $4
WHERE disease_id = $1
`

type UpdateDiseaseParams struct {
	DiseaseID uuid.UUID `db:"disease_id"`
	Name      string    `db:"name"`
	Code      string    `db:"code"`
	UpdatedAt time.Time `db:"updated_at"`
}

func (q *Queries) UpdateDisease(ctx context.Context, arg UpdateDiseaseParams) error {
	_, err := q.db.ExecContext(ctx, UpdateDisease,
		arg.DiseaseID,
		arg.Name,
		arg.Code,
		arg.UpdatedAt,
	)
	return err
}
