// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: disease_metric_overrides.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const CreateDiseaseMetricOverride = `-- name: CreateDiseaseMetricOverride :exec
INSERT INTO disease_metric_overrides (
    disease_id,
    metric_type_id,
    min_value,
    max_value,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateDiseaseMetricOverrideParams struct {
	DiseaseID    uuid.UUID `db:"disease_id"`
	MetricTypeID uuid.UUID `db:"metric_type_id"`
	MinValue     float64   `db:"min_value"`
	MaxValue     float64   `db:"max_value"`
	CreatedAt    time.Time `db:"created_at"`
	UpdatedAt    time.Time `db:"updated_at"`
}

func (q *Queries) CreateDiseaseMetricOverride(ctx context.Context, arg CreateDiseaseMetricOverrideParams) error {
	_, err := q.db.ExecContext(ctx, CreateDiseaseMetricOverride,
		arg.DiseaseID,
		arg.MetricTypeID,
		arg.MinValue,
		arg.MaxValue,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const DeleteDiseaseMetricOverride = `-- name: DeleteDiseaseMetricOverride :exec
DELETE FROM disease_metric_overrides
WHERE disease_id = $1 AND metric_type_id = $2
`

type DeleteDiseaseMetricOverrideParams struct {
	DiseaseID    uuid.UUID `db:"disease_id"`
	MetricTypeID uuid.UUID `db:"metric_type_id"`
}

func (q *Queries) DeleteDiseaseMetricOverride(ctx context.Context, arg DeleteDiseaseMetricOverrideParams) error {
	_, err := q.db.ExecContext(ctx, DeleteDiseaseMetricOverride, arg.DiseaseID, arg.MetricTypeID)
	return err
}

const DeleteDiseaseMetricOverridesByDisease = `-- name: DeleteDiseaseMetricOverridesByDisease :exec
DELETE FROM disease_metric_overrides
WHERE disease_id = $1
`

func (q *Queries) DeleteDiseaseMetricOverridesByDisease(ctx context.Context, diseaseID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, DeleteDiseaseMetricOverridesByDisease, diseaseID)
	return err
}

const GetDiseaseMetricOverride = `-- name: GetDiseaseMetricOverride :one
SELECT disease_id, metric_type_id, min_value, max_value, created_at, updated_at
FROM disease_metric_overrides
WHERE disease_id = $1 AND metric_type_id = $2
LIMIT 1
`

type GetDiseaseMetricOverrideParams struct {
	DiseaseID    uuid.UUID `db:"disease_id"`
	MetricTypeID uuid.UUID `db:"metric_type_id"`
}

func (q *Queries) GetDiseaseMetricOverride(ctx context.Context, arg GetDiseaseMetricOverrideParams) (DiseaseMetricOverride, error) {
	row := q.db.QueryRowContext(ctx, GetDiseaseMetricOverride, arg.DiseaseID, arg.MetricTypeID)
	var i DiseaseMetricOverride
	err := row.Scan(
		&i.DiseaseID,
		&i.MetricTypeID,
		&i.MinValue,
		&i.MaxValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListAllDiseaseMetricOverrides = `-- name: ListAllDiseaseMetricOverrides :many
SELECT disease_id, metric_type_id, min_value, max_value, created_at, updated_at
FROM disease_metric_overrides
`

func (q *Queries) ListAllDiseaseMetricOverrides(ctx context.Context) ([]DiseaseMetricOverride, error) {
	rows, err := q.db.QueryContext(ctx, ListAllDiseaseMetricOverrides)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiseaseMetricOverride{}
	for rows.Next() {
		var i DiseaseMetricOverride
		if err := rows.Scan(
			&i.DiseaseID,
			&i.MetricTypeID,
			&i.MinValue,
			&i.MaxValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListDiseaseMetricOverridesByDisease = `-- name: ListDiseaseMetricOverridesByDisease :many
SELECT disease_id, metric_type_id, min_value, max_value, created_at, updated_at
FROM disease_metric_overrides
WHERE disease_id = $1
`

func (q *Queries) ListDiseaseMetricOverridesByDisease(ctx context.Context, diseaseID uuid.UUID) ([]DiseaseMetricOverride, error) {
	rows, err := q.db.QueryContext(ctx, ListDiseaseMetricOverridesByDisease, diseaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiseaseMetricOverride{}
	for rows.Next() {
		var i DiseaseMetricOverride
		if err := rows.Scan(
			&i.DiseaseID,
			&i.MetricTypeID,
			&i.MinValue,
			&i.MaxValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListDiseaseMetricOverridesByMetricType = `-- name: ListDiseaseMetricOverridesByMetricType :many
SELECT disease_id, metric_type_id, min_value, max_value, created_at, updated_at
FROM disease_metric_overrides
WHERE metric_type_id = $1
`

func (q *Queries) ListDiseaseMetricOverridesByMetricType(ctx context.Context, metricTypeID uuid.UUID) ([]DiseaseMetricOverride, error) {
	rows, err := q.db.QueryContext(ctx, ListDiseaseMetricOverridesByMetricType, metricTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiseaseMetricOverride{}
	for rows.Next() {
		var i DiseaseMetricOverride
		if err := rows.Scan(
			&i.DiseaseID,
			&i.MetricTypeID,
			&i.MinValue,
			&i.MaxValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateDiseaseMetricOverride = `-- name: UpdateDiseaseMetricOverride :exec
UPDATE disease_metric_overrides
SET
    min_value  = $3,
    max_value  = $4,
    updated_at = $5
WHERE disease_id = $1 AND metric_type_id = $2
`

type UpdateDiseaseMetricOverrideParams struct {
	DiseaseID    uuid.UUID `db:"disease_id"`
	MetricTypeID uuid.UUID `db:"metric_type_id"`
	MinValue     float64   `db:"min_value"`
	MaxValue     float64   `db:"max_value"`
	UpdatedAt    time.Time `db:"updated_at"`
}

func (q *Queries) UpdateDiseaseMetricOverride(ctx context.Context, arg UpdateDiseaseMetricOverrideParams) error {
	_, err := q.db.ExecContext(ctx, UpdateDiseaseMetricOverride,
		arg.DiseaseID,
		arg.MetricTypeID,
		arg.MinValue,
		arg.MaxValue,
		arg.UpdatedAt,
	)
	return err
}
