// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: disease_sensors.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const CountDiseaseSensorsByDisease = `-- name: CountDiseaseSensorsByDisease :one
SELECT COUNT(*)
FROM disease_sensors
WHERE disease_id = $1
`

func (q *Queries) CountDiseaseSensorsByDisease(ctx context.Context, diseaseID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountDiseaseSensorsByDisease, diseaseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountDiseaseSensorsBySensor = `-- name: CountDiseaseSensorsBySensor :one
SELECT COUNT(*)
FROM disease_sensors
WHERE sensor_id = $1
`

func (q *Queries) CountDiseaseSensorsBySensor(ctx context.Context, sensorID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountDiseaseSensorsBySensor, sensorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateDiseaseSensor = `-- name: CreateDiseaseSensor :exec
INSERT INTO disease_sensors (
    disease_id,
    sensor_id,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4)
`

type CreateDiseaseSensorParams struct {
	DiseaseID uuid.UUID `db:"disease_id"`
	SensorID  uuid.UUID `db:"sensor_id"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

// SQL constants for mutations (used in repository)
func (q *Queries) CreateDiseaseSensor(ctx context.Context, arg CreateDiseaseSensorParams) error {
	_, err := q.db.ExecContext(ctx, CreateDiseaseSensor,
		arg.DiseaseID,
		arg.SensorID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const DeleteDiseaseSensor = `-- name: DeleteDiseaseSensor :exec
DELETE FROM disease_sensors
WHERE disease_id = $1 AND sensor_id = $2
`

type DeleteDiseaseSensorParams struct {
	DiseaseID uuid.UUID `db:"disease_id"`
	SensorID  uuid.UUID `db:"sensor_id"`
}

func (q *Queries) DeleteDiseaseSensor(ctx context.Context, arg DeleteDiseaseSensorParams) error {
	_, err := q.db.ExecContext(ctx, DeleteDiseaseSensor, arg.DiseaseID, arg.SensorID)
	return err
}

const DeleteDiseaseSensorsByDisease = `-- name: DeleteDiseaseSensorsByDisease :exec
DELETE FROM disease_sensors
WHERE disease_id = $1
`

func (q *Queries) DeleteDiseaseSensorsByDisease(ctx context.Context, diseaseID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, DeleteDiseaseSensorsByDisease, diseaseID)
	return err
}

const DeleteDiseaseSensorsBySensor = `-- name: DeleteDiseaseSensorsBySensor :exec
DELETE FROM disease_sensors
WHERE sensor_id = $1
`

func (q *Queries) DeleteDiseaseSensorsBySensor(ctx context.Context, sensorID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, DeleteDiseaseSensorsBySensor, sensorID)
	return err
}

const GetDiseaseSensor = `-- name: GetDiseaseSensor :one
SELECT disease_id, sensor_id, created_at, updated_at
FROM disease_sensors
WHERE disease_id = $1 AND sensor_id = $2
LIMIT 1
`

type GetDiseaseSensorParams struct {
	DiseaseID uuid.UUID `db:"disease_id"`
	SensorID  uuid.UUID `db:"sensor_id"`
}

func (q *Queries) GetDiseaseSensor(ctx context.Context, arg GetDiseaseSensorParams) (DiseaseSensor, error) {
	row := q.db.QueryRowContext(ctx, GetDiseaseSensor, arg.DiseaseID, arg.SensorID)
	var i DiseaseSensor
	err := row.Scan(
		&i.DiseaseID,
		&i.SensorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListAllDiseaseSensors = `-- name: ListAllDiseaseSensors :many
SELECT disease_id, sensor_id, created_at, updated_at
FROM disease_sensors
ORDER BY created_at DESC
`

func (q *Queries) ListAllDiseaseSensors(ctx context.Context) ([]DiseaseSensor, error) {
	rows, err := q.db.QueryContext(ctx, ListAllDiseaseSensors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiseaseSensor{}
	for rows.Next() {
		var i DiseaseSensor
		if err := rows.Scan(
			&i.DiseaseID,
			&i.SensorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListDiseaseSensorsByDisease = `-- name: ListDiseaseSensorsByDisease :many
SELECT disease_id, sensor_id, created_at, updated_at
FROM disease_sensors
WHERE disease_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDiseaseSensorsByDisease(ctx context.Context, diseaseID uuid.UUID) ([]DiseaseSensor, error) {
	rows, err := q.db.QueryContext(ctx, ListDiseaseSensorsByDisease, diseaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiseaseSensor{}
	for rows.Next() {
		var i DiseaseSensor
		if err := rows.Scan(
			&i.DiseaseID,
			&i.SensorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListDiseaseSensorsBySensor = `-- name: ListDiseaseSensorsBySensor :many
SELECT disease_id, sensor_id, created_at, updated_at
FROM disease_sensors
WHERE sensor_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDiseaseSensorsBySensor(ctx context.Context, sensorID uuid.UUID) ([]DiseaseSensor, error) {
	rows, err := q.db.QueryContext(ctx, ListDiseaseSensorsBySensor, sensorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiseaseSensor{}
	for rows.Next() {
		var i DiseaseSensor
		if err := rows.Scan(
			&i.DiseaseID,
			&i.SensorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateDiseaseSensor = `-- name: UpdateDiseaseSensor :exec
UPDATE disease_sensors
SET
    updated_at = $3
WHERE disease_id = $1 AND sensor_id = $2
`

type UpdateDiseaseSensorParams struct {
	DiseaseID uuid.UUID `db:"disease_id"`
	SensorID  uuid.UUID `db:"sensor_id"`
	UpdatedAt time.Time `db:"updated_at"`
}

func (q *Queries) UpdateDiseaseSensor(ctx context.Context, arg UpdateDiseaseSensorParams) error {
	_, err := q.db.ExecContext(ctx, UpdateDiseaseSensor, arg.DiseaseID, arg.SensorID, arg.UpdatedAt)
	return err
}
