// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: metric_types.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const CountMetricTypesBySensor = `-- name: CountMetricTypesBySensor :one
SELECT COUNT(*) FROM metric_types
WHERE sensor_id = $1
`

func (q *Queries) CountMetricTypesBySensor(ctx context.Context, sensorID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountMetricTypesBySensor, sensorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateMetricType = `-- name: CreateMetricType :exec
INSERT INTO metric_types (
    metric_type_id,
    sensor_id,
    code,
    name,
    symbol,
    min_value,
    max_value,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateMetricTypeParams struct {
	MetricTypeID uuid.UUID `db:"metric_type_id"`
	SensorID     uuid.UUID `db:"sensor_id"`
	Code         string    `db:"code"`
	Name         string    `db:"name"`
	Symbol       string    `db:"symbol"`
	MinValue     float64   `db:"min_value"`
	MaxValue     float64   `db:"max_value"`
	CreatedAt    time.Time `db:"created_at"`
	UpdatedAt    time.Time `db:"updated_at"`
}

func (q *Queries) CreateMetricType(ctx context.Context, arg CreateMetricTypeParams) error {
	_, err := q.db.ExecContext(ctx, CreateMetricType,
		arg.MetricTypeID,
		arg.SensorID,
		arg.Code,
		arg.Name,
		arg.Symbol,
		arg.MinValue,
		arg.MaxValue,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const DeleteMetricType = `-- name: DeleteMetricType :exec
DELETE FROM metric_types
WHERE metric_type_id = $1
`

func (q *Queries) DeleteMetricType(ctx context.Context, metricTypeID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, DeleteMetricType, metricTypeID)
	return err
}

const DeleteMetricTypesBySensor = `-- name: DeleteMetricTypesBySensor :exec
DELETE FROM metric_types
WHERE sensor_id = $1
`

func (q *Queries) DeleteMetricTypesBySensor(ctx context.Context, sensorID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, DeleteMetricTypesBySensor, sensorID)
	return err
}

const GetMetricType = `-- name: GetMetricType :one
SELECT metric_type_id, sensor_id, code, name, symbol, min_value, max_value, created_at, updated_at
FROM metric_types
WHERE metric_type_id = $1
LIMIT 1
`

func (q *Queries) GetMetricType(ctx context.Context, metricTypeID uuid.UUID) (MetricType, error) {
	row := q.db.QueryRowContext(ctx, GetMetricType, metricTypeID)
	var i MetricType
	err := row.Scan(
		&i.MetricTypeID,
		&i.SensorID,
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.MinValue,
		&i.MaxValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetMetricTypeBySensorAndCode = `-- name: GetMetricTypeBySensorAndCode :one
SELECT metric_type_id, sensor_id, code, name, symbol, min_value, max_value, created_at, updated_at
FROM metric_types
WHERE sensor_id = $1 AND code = $2
LIMIT 1
`

type GetMetricTypeBySensorAndCodeParams struct {
	SensorID uuid.UUID `db:"sensor_id"`
	Code     string    `db:"code"`
}

func (q *Queries) GetMetricTypeBySensorAndCode(ctx context.Context, arg GetMetricTypeBySensorAndCodeParams) (MetricType, error) {
	row := q.db.QueryRowContext(ctx, GetMetricTypeBySensorAndCode, arg.SensorID, arg.Code)
	var i MetricType
	err := row.Scan(
		&i.MetricTypeID,
		&i.SensorID,
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.MinValue,
		&i.MaxValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListMetricTypes = `-- name: ListMetricTypes :many
SELECT metric_type_id, sensor_id, code, name, symbol, min_value, max_value, created_at, updated_at
FROM metric_types
ORDER BY sensor_id, code
`

func (q *Queries) ListMetricTypes(ctx context.Context) ([]MetricType, error) {
	rows, err := q.db.QueryContext(ctx, ListMetricTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetricType{}
	for rows.Next() {
		var i MetricType
		if err := rows.Scan(
			&i.MetricTypeID,
			&i.SensorID,
			&i.Code,
			&i.Name,
			&i.Symbol,
			&i.MinValue,
			&i.MaxValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListMetricTypesBySensor = `-- name: ListMetricTypesBySensor :many
SELECT metric_type_id, sensor_id, code, name, symbol, min_value, max_value, created_at, updated_at
FROM metric_types
WHERE sensor_id = $1
ORDER BY code
`

func (q *Queries) ListMetricTypesBySensor(ctx context.Context, sensorID uuid.UUID) ([]MetricType, error) {
	rows, err := q.db.QueryContext(ctx, ListMetricTypesBySensor, sensorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetricType{}
	for rows.Next() {
		var i MetricType
		if err := rows.Scan(
			&i.MetricTypeID,
			&i.SensorID,
			&i.Code,
			&i.Name,
			&i.Symbol,
			&i.MinValue,
			&i.MaxValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateMetricType = `-- name: UpdateMetricType :exec
UPDATE metric_types
SET
    code       = $2,
    name       = $3,
    symbol     = $4,
    min_value  = $5,
    max_value  = $6,
    updated_at = $7
WHERE metric_type_id = $1
`

type UpdateMetricTypeParams struct {
	MetricTypeID uuid.UUID `db:"metric_type_id"`
	Code         string    `db:"code"`
	Name         string    `db:"name"`
	Symbol       string    `db:"symbol"`
	MinValue     float64   `db:"min_value"`
	MaxValue     float64   `db:"max_value"`
	UpdatedAt    time.Time `db:"updated_at"`
}

func (q *Queries) UpdateMetricType(ctx context.Context, arg UpdateMetricTypeParams) error {
	_, err := q.db.ExecContext(ctx, UpdateMetricType,
		arg.MetricTypeID,
		arg.Code,
		arg.Name,
		arg.Symbol,
		arg.MinValue,
		arg.MaxValue,
		arg.UpdatedAt,
	)
	return err
}
