// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"time"

	"github.com/google/uuid"
)

type Disease struct {
	DiseaseID uuid.UUID `db:"disease_id"`
	Name      string    `db:"name"`
	Code      string    `db:"code"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

type DiseaseMetricOverride struct {
	DiseaseID    uuid.UUID `db:"disease_id"`
	MetricTypeID uuid.UUID `db:"metric_type_id"`
	MinValue     float64   `db:"min_value"`
	MaxValue     float64   `db:"max_value"`
	CreatedAt    time.Time `db:"created_at"`
	UpdatedAt    time.Time `db:"updated_at"`
}

type DiseaseSensor struct {
	DiseaseID uuid.UUID `db:"disease_id"`
	SensorID  uuid.UUID `db:"sensor_id"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

type MetricType struct {
	MetricTypeID uuid.UUID `db:"metric_type_id"`
	SensorID     uuid.UUID `db:"sensor_id"`
	Code         string    `db:"code"`
	Name         string    `db:"name"`
	Symbol       string    `db:"symbol"`
	MinValue     float64   `db:"min_value"`
	MaxValue     float64   `db:"max_value"`
	CreatedAt    time.Time `db:"created_at"`
	UpdatedAt    time.Time `db:"updated_at"`
}

type Sensor struct {
	SensorID  uuid.UUID `db:"sensor_id"`
	Name      string    `db:"name"`
	Code      string    `db:"code"`
	Symbol    string    `db:"symbol"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

type SensorPatient struct {
	SensorID  uuid.UUID `db:"sensor_id"`
	PatientID uuid.UUID `db:"patient_id"`
	Status    string    `db:"status"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

type SensorPatientMetric struct {
	SensorID  uuid.UUID `db:"sensor_id"`
	PatientID uuid.UUID `db:"patient_id"`
	MetricID  uuid.UUID `db:"metric_id"`
	Value     float64   `db:"value"`
	Symbol    string    `db:"symbol"`
	CreatedAt time.Time `db:"created_at"`
}
