// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"time"

	"github.com/google/uuid"
)

type SensorMetric struct {
	SensorID  uuid.UUID `db:"sensor_id"`
	MetricID  uuid.UUID `db:"metric_id"`
	Value     float64   `db:"value"`
	CreatedAt time.Time `db:"created_at"`
}
