// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sensor_patients.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const CountSensorPatientsByPatient = `-- name: CountSensorPatientsByPatient :one
SELECT COUNT(*)
FROM sensor_patients
WHERE patient_id = $1
`

func (q *Queries) CountSensorPatientsByPatient(ctx context.Context, patientID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountSensorPatientsByPatient, patientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountSensorPatientsBySensor = `-- name: CountSensorPatientsBySensor :one
SELECT COUNT(*)
FROM sensor_patients
WHERE sensor_id = $1
`

func (q *Queries) CountSensorPatientsBySensor(ctx context.Context, sensorID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountSensorPatientsBySensor, sensorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateSensorPatient = `-- name: CreateSensorPatient :exec
INSERT INTO sensor_patients (
    sensor_id,
    patient_id,
    status,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5)
`

type CreateSensorPatientParams struct {
	SensorID  uuid.UUID `db:"sensor_id"`
	PatientID uuid.UUID `db:"patient_id"`
	Status    string    `db:"status"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

// SQL constants for mutations (used in repository)
func (q *Queries) CreateSensorPatient(ctx context.Context, arg CreateSensorPatientParams) error {
	_, err := q.db.ExecContext(ctx, CreateSensorPatient,
		arg.SensorID,
		arg.PatientID,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const DeleteSensorPatient = `-- name: DeleteSensorPatient :exec
DELETE FROM sensor_patients
WHERE sensor_id = $1 AND patient_id = $2
`

type DeleteSensorPatientParams struct {
	SensorID  uuid.UUID `db:"sensor_id"`
	PatientID uuid.UUID `db:"patient_id"`
}

func (q *Queries) DeleteSensorPatient(ctx context.Context, arg DeleteSensorPatientParams) error {
	_, err := q.db.ExecContext(ctx, DeleteSensorPatient, arg.SensorID, arg.PatientID)
	return err
}

const DeleteSensorPatientsByPatient = `-- name: DeleteSensorPatientsByPatient :exec
DELETE FROM sensor_patients
WHERE patient_id = $1
`

func (q *Queries) DeleteSensorPatientsByPatient(ctx context.Context, patientID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, DeleteSensorPatientsByPatient, patientID)
	return err
}

const DeleteSensorPatientsBySensor = `-- name: DeleteSensorPatientsBySensor :exec
DELETE FROM sensor_patients
WHERE sensor_id = $1
`

func (q *Queries) DeleteSensorPatientsBySensor(ctx context.Context, sensorID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, DeleteSensorPatientsBySensor, sensorID)
	return err
}

const GetSensorPatient = `-- name: GetSensorPatient :one
SELECT sensor_id, patient_id, status, created_at, updated_at
FROM sensor_patients
WHERE sensor_id = $1 AND patient_id = $2
LIMIT 1
`

type GetSensorPatientParams struct {
	SensorID  uuid.UUID `db:"sensor_id"`
	PatientID uuid.UUID `db:"patient_id"`
}

func (q *Queries) GetSensorPatient(ctx context.Context, arg GetSensorPatientParams) (SensorPatient, error) {
	row := q.db.QueryRowContext(ctx, GetSensorPatient, arg.SensorID, arg.PatientID)
	var i SensorPatient
	err := row.Scan(
		&i.SensorID,
		&i.PatientID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListAllSensorPatients = `-- name: ListAllSensorPatients :many
SELECT sensor_id, patient_id, status, created_at, updated_at
FROM sensor_patients
ORDER BY created_at DESC
`

func (q *Queries) ListAllSensorPatients(ctx context.Context) ([]SensorPatient, error) {
	rows, err := q.db.QueryContext(ctx, ListAllSensorPatients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SensorPatient{}
	for rows.Next() {
		var i SensorPatient
		if err := rows.Scan(
			&i.SensorID,
			&i.PatientID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListSensorPatientsByPatient = `-- name: ListSensorPatientsByPatient :many
SELECT sensor_id, patient_id, status, created_at, updated_at
FROM sensor_patients
WHERE patient_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSensorPatientsByPatient(ctx context.Context, patientID uuid.UUID) ([]SensorPatient, error) {
	rows, err := q.db.QueryContext(ctx, ListSensorPatientsByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SensorPatient{}
	for rows.Next() {
		var i SensorPatient
		if err := rows.Scan(
			&i.SensorID,
			&i.PatientID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListSensorPatientsBySensor = `-- name: ListSensorPatientsBySensor :many
SELECT sensor_id, patient_id, status, created_at, updated_at
FROM sensor_patients
WHERE sensor_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSensorPatientsBySensor(ctx context.Context, sensorID uuid.UUID) ([]SensorPatient, error) {
	rows, err := q.db.QueryContext(ctx, ListSensorPatientsBySensor, sensorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SensorPatient{}
	for rows.Next() {
		var i SensorPatient
		if err := rows.Scan(
			&i.SensorID,
			&i.PatientID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListSensorPatientsByStatus = `-- name: ListSensorPatientsByStatus :many
SELECT sensor_id, patient_id, status, created_at, updated_at
FROM sensor_patients
WHERE status = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSensorPatientsByStatus(ctx context.Context, status string) ([]SensorPatient, error) {
	rows, err := q.db.QueryContext(ctx, ListSensorPatientsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SensorPatient{}
	for rows.Next() {
		var i SensorPatient
		if err := rows.Scan(
			&i.SensorID,
			&i.PatientID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateSensorPatient = `-- name: UpdateSensorPatient :exec
UPDATE sensor_patients
SET
    status = $3,
    updated_at = $4
WHERE sensor_id = $1 AND patient_id = $2
`

type UpdateSensorPatientParams struct {
	SensorID  uuid.UUID `db:"sensor_id"`
	PatientID uuid.UUID `db:"patient_id"`
	Status    string    `db:"status"`
	UpdatedAt time.Time `db:"updated_at"`
}

func (q *Queries) UpdateSensorPatient(ctx context.Context, arg UpdateSensorPatientParams) error {
	_, err := q.db.ExecContext(ctx, UpdateSensorPatient,
		arg.SensorID,
		arg.PatientID,
		arg.Status,
		arg.UpdatedAt,
	)
	return err
}
