// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sensor_metrics.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const CountSensorMetrics = `-- name: CountSensorMetrics :one
SELECT COUNT(*) FROM sensor_metrics
`

func (q *Queries) CountSensorMetrics(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountSensorMetrics)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateSensorMetric = `-- name: CreateSensorMetric :exec
INSERT INTO sensor_metrics (
    sensor_id,
    metric_id,
    value,
    created_at
) VALUES ($1, $2, $3, $4)
`

type CreateSensorMetricParams struct {
	SensorID  uuid.UUID `db:"sensor_id"`
	MetricID  uuid.UUID `db:"metric_id"`
	Value     float64   `db:"value"`
	CreatedAt time.Time `db:"created_at"`
}

// SQL constants for mutations (used in repository)
func (q *Queries) CreateSensorMetric(ctx context.Context, arg CreateSensorMetricParams) error {
	_, err := q.db.ExecContext(ctx, CreateSensorMetric,
		arg.SensorID,
		arg.MetricID,
		arg.Value,
		arg.CreatedAt,
	)
	return err
}

const DeleteSensorMetric = `-- name: DeleteSensorMetric :exec
DELETE FROM sensor_metrics
WHERE sensor_id = $1 AND metric_id = $2
`

type DeleteSensorMetricParams struct {
	SensorID uuid.UUID `db:"sensor_id"`
	MetricID uuid.UUID `db:"metric_id"`
}

func (q *Queries) DeleteSensorMetric(ctx context.Context, arg DeleteSensorMetricParams) error {
	_, err := q.db.ExecContext(ctx, DeleteSensorMetric, arg.SensorID, arg.MetricID)
	return err
}

const GetSensorMetric = `-- name: GetSensorMetric :one
SELECT sensor_id, metric_id, value, created_at
FROM sensor_metrics
WHERE sensor_id = $1 AND metric_id = $2
LIMIT 1
`

type GetSensorMetricParams struct {
	SensorID uuid.UUID `db:"sensor_id"`
	MetricID uuid.UUID `db:"metric_id"`
}

func (q *Queries) GetSensorMetric(ctx context.Context, arg GetSensorMetricParams) (SensorMetric, error) {
	row := q.db.QueryRowContext(ctx, GetSensorMetric, arg.SensorID, arg.MetricID)
	var i SensorMetric
	err := row.Scan(
		&i.SensorID,
		&i.MetricID,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const ListSensorMetrics = `-- name: ListSensorMetrics :many
SELECT sensor_id, metric_id, value, created_at
FROM sensor_metrics
ORDER BY created_at DESC
`

func (q *Queries) ListSensorMetrics(ctx context.Context) ([]SensorMetric, error) {
	rows, err := q.db.QueryContext(ctx, ListSensorMetrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SensorMetric{}
	for rows.Next() {
		var i SensorMetric
		if err := rows.Scan(
			&i.SensorID,
			&i.MetricID,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListSensorMetricsBySensorID = `-- name: ListSensorMetricsBySensorID :many
SELECT sensor_id, metric_id, value, created_at
FROM sensor_metrics
WHERE sensor_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSensorMetricsBySensorID(ctx context.Context, sensorID uuid.UUID) ([]SensorMetric, error) {
	rows, err := q.db.QueryContext(ctx, ListSensorMetricsBySensorID, sensorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SensorMetric{}
	for rows.Next() {
		var i SensorMetric
		if err := rows.Scan(
			&i.SensorID,
			&i.MetricID,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateSensorMetric = `-- name: UpdateSensorMetric :exec
UPDATE sensor_metrics
SET
    value = $3
WHERE sensor_id = $1 AND metric_id = $2
`

type UpdateSensorMetricParams struct {
	SensorID uuid.UUID `db:"sensor_id"`
	MetricID uuid.UUID `db:"metric_id"`
	Value    float64   `db:"value"`
}

func (q *Queries) UpdateSensorMetric(ctx context.Context, arg UpdateSensorMetricParams) error {
	_, err := q.db.ExecContext(ctx, UpdateSensorMetric, arg.SensorID, arg.MetricID, arg.Value)
	return err
}
