// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sensor_patient_metrics.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const CountSensorPatientMetrics = `-- name: CountSensorPatientMetrics :one
SELECT COUNT(*)
FROM sensor_patient_metrics
WHERE sensor_id = $1 AND patient_id = $2
`

type CountSensorPatientMetricsParams struct {
	SensorID  uuid.UUID `db:"sensor_id"`
	PatientID uuid.UUID `db:"patient_id"`
}

func (q *Queries) CountSensorPatientMetrics(ctx context.Context, arg CountSensorPatientMetricsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountSensorPatientMetrics, arg.SensorID, arg.PatientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateSensorPatientMetric = `-- name: CreateSensorPatientMetric :exec
INSERT INTO sensor_patient_metrics (
    sensor_id,
    patient_id,
    metric_id,
    value,
    created_at
) VALUES ($1, $2, $3, $4, $5)
`

type CreateSensorPatientMetricParams struct {
	SensorID  uuid.UUID `db:"sensor_id"`
	PatientID uuid.UUID `db:"patient_id"`
	MetricID  uuid.UUID `db:"metric_id"`
	Value     float64   `db:"value"`
	CreatedAt time.Time `db:"created_at"`
}

// SQL constants for mutations (used in repository)
func (q *Queries) CreateSensorPatientMetric(ctx context.Context, arg CreateSensorPatientMetricParams) error {
	_, err := q.db.ExecContext(ctx, CreateSensorPatientMetric,
		arg.SensorID,
		arg.PatientID,
		arg.MetricID,
		arg.Value,
		arg.CreatedAt,
	)
	return err
}

const DeleteSensorPatientMetric = `-- name: DeleteSensorPatientMetric :exec
DELETE FROM sensor_patient_metrics
WHERE sensor_id = $1 AND patient_id = $2 AND metric_id = $3 AND created_at = $4
`

type DeleteSensorPatientMetricParams struct {
	SensorID  uuid.UUID `db:"sensor_id"`
	PatientID uuid.UUID `db:"patient_id"`
	MetricID  uuid.UUID `db:"metric_id"`
	CreatedAt time.Time `db:"created_at"`
}

func (q *Queries) DeleteSensorPatientMetric(ctx context.Context, arg DeleteSensorPatientMetricParams) error {
	_, err := q.db.ExecContext(ctx, DeleteSensorPatientMetric,
		arg.SensorID,
		arg.PatientID,
		arg.MetricID,
		arg.CreatedAt,
	)
	return err
}

const DeleteSensorPatientMetrics = `-- name: DeleteSensorPatientMetrics :exec
DELETE FROM sensor_patient_metrics
WHERE sensor_id = $1 AND patient_id = $2
`

type DeleteSensorPatientMetricsParams struct {
	SensorID  uuid.UUID `db:"sensor_id"`
	PatientID uuid.UUID `db:"patient_id"`
}

func (q *Queries) DeleteSensorPatientMetrics(ctx context.Context, arg DeleteSensorPatientMetricsParams) error {
	_, err := q.db.ExecContext(ctx, DeleteSensorPatientMetrics, arg.SensorID, arg.PatientID)
	return err
}

const DeleteSensorPatientMetricsByMetric = `-- name: DeleteSensorPatientMetricsByMetric :exec
DELETE FROM sensor_patient_metrics
WHERE metric_id = $1
`

func (q *Queries) DeleteSensorPatientMetricsByMetric(ctx context.Context, metricID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, DeleteSensorPatientMetricsByMetric, metricID)
	return err
}

const DeleteSensorPatientMetricsByPatient = `-- name: DeleteSensorPatientMetricsByPatient :exec
DELETE FROM sensor_patient_metrics
WHERE patient_id = $1
`

func (q *Queries) DeleteSensorPatientMetricsByPatient(ctx context.Context, patientID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, DeleteSensorPatientMetricsByPatient, patientID)
	return err
}

const DeleteSensorPatientMetricsBySensor = `-- name: DeleteSensorPatientMetricsBySensor :exec
DELETE FROM sensor_patient_metrics
WHERE sensor_id = $1
`

func (q *Queries) DeleteSensorPatientMetricsBySensor(ctx context.Context, sensorID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, DeleteSensorPatientMetricsBySensor, sensorID)
	return err
}

const GetLatestSensorPatientMetric = `-- name: GetLatestSensorPatientMetric :one
SELECT sensor_id, patient_id, metric_id, value, created_at
FROM sensor_patient_metrics
WHERE sensor_id = $1 AND patient_id = $2 AND metric_id = $3
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestSensorPatientMetricParams struct {
	SensorID  uuid.UUID `db:"sensor_id"`
	PatientID uuid.UUID `db:"patient_id"`
	MetricID  uuid.UUID `db:"metric_id"`
}

func (q *Queries) GetLatestSensorPatientMetric(ctx context.Context, arg GetLatestSensorPatientMetricParams) (SensorPatientMetric, error) {
	row := q.db.QueryRowContext(ctx, GetLatestSensorPatientMetric, arg.SensorID, arg.PatientID, arg.MetricID)
	var i SensorPatientMetric
	err := row.Scan(
		&i.SensorID,
		&i.PatientID,
		&i.MetricID,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const GetSensorPatientMetric = `-- name: GetSensorPatientMetric :one
SELECT sensor_id, patient_id, metric_id, value, created_at
FROM sensor_patient_metrics
WHERE sensor_id = $1 AND patient_id = $2 AND metric_id = $3 AND created_at = $4
LIMIT 1
`

type GetSensorPatientMetricParams struct {
	SensorID  uuid.UUID `db:"sensor_id"`
	PatientID uuid.UUID `db:"patient_id"`
	MetricID  uuid.UUID `db:"metric_id"`
	CreatedAt time.Time `db:"created_at"`
}

func (q *Queries) GetSensorPatientMetric(ctx context.Context, arg GetSensorPatientMetricParams) (SensorPatientMetric, error) {
	row := q.db.QueryRowContext(ctx, GetSensorPatientMetric,
		arg.SensorID,
		arg.PatientID,
		arg.MetricID,
		arg.CreatedAt,
	)
	var i SensorPatientMetric
	err := row.Scan(
		&i.SensorID,
		&i.PatientID,
		&i.MetricID,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const ListSensorPatientMetrics = `-- name: ListSensorPatientMetrics :many
SELECT sensor_id, patient_id, metric_id, value, created_at
FROM sensor_patient_metrics
WHERE sensor_id = $1 AND patient_id = $2
ORDER BY created_at DESC
`

type ListSensorPatientMetricsParams struct {
	SensorID  uuid.UUID `db:"sensor_id"`
	PatientID uuid.UUID `db:"patient_id"`
}

func (q *Queries) ListSensorPatientMetrics(ctx context.Context, arg ListSensorPatientMetricsParams) ([]SensorPatientMetric, error) {
	rows, err := q.db.QueryContext(ctx, ListSensorPatientMetrics, arg.SensorID, arg.PatientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SensorPatientMetric{}
	for rows.Next() {
		var i SensorPatientMetric
		if err := rows.Scan(
			&i.SensorID,
			&i.PatientID,
			&i.MetricID,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListSensorPatientMetricsByMetric = `-- name: ListSensorPatientMetricsByMetric :many
SELECT sensor_id, patient_id, metric_id, value, created_at
FROM sensor_patient_metrics
WHERE metric_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSensorPatientMetricsByMetric(ctx context.Context, metricID uuid.UUID) ([]SensorPatientMetric, error) {
	rows, err := q.db.QueryContext(ctx, ListSensorPatientMetricsByMetric, metricID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SensorPatientMetric{}
	for rows.Next() {
		var i SensorPatientMetric
		if err := rows.Scan(
			&i.SensorID,
			&i.PatientID,
			&i.MetricID,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListSensorPatientMetricsByPatient = `-- name: ListSensorPatientMetricsByPatient :many
SELECT sensor_id, patient_id, metric_id, value, created_at
FROM sensor_patient_metrics
WHERE patient_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSensorPatientMetricsByPatient(ctx context.Context, patientID uuid.UUID) ([]SensorPatientMetric, error) {
	rows, err := q.db.QueryContext(ctx, ListSensorPatientMetricsByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SensorPatientMetric{}
	for rows.Next() {
		var i SensorPatientMetric
		if err := rows.Scan(
			&i.SensorID,
			&i.PatientID,
			&i.MetricID,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListSensorPatientMetricsBySensor = `-- name: ListSensorPatientMetricsBySensor :many
SELECT sensor_id, patient_id, metric_id, value, created_at
FROM sensor_patient_metrics
WHERE sensor_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSensorPatientMetricsBySensor(ctx context.Context, sensorID uuid.UUID) ([]SensorPatientMetric, error) {
	rows, err := q.db.QueryContext(ctx, ListSensorPatientMetricsBySensor, sensorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SensorPatientMetric{}
	for rows.Next() {
		var i SensorPatientMetric
		if err := rows.Scan(
			&i.SensorID,
			&i.PatientID,
			&i.MetricID,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListSensorPatientMetricsByTimeRange = `-- name: ListSensorPatientMetricsByTimeRange :many
SELECT sensor_id, patient_id, metric_id, value, created_at
FROM sensor_patient_metrics
WHERE sensor_id = $1
    AND patient_id = $2
    AND created_at >= $3
    AND created_at <= $4
ORDER BY created_at DESC
`

type ListSensorPatientMetricsByTimeRangeParams struct {
	SensorID    uuid.UUID `db:"sensor_id"`
	PatientID   uuid.UUID `db:"patient_id"`
	CreatedAt   time.Time `db:"created_at"`
	CreatedAt_2 time.Time `db:"created_at_2"`
}

func (q *Queries) ListSensorPatientMetricsByTimeRange(ctx context.Context, arg ListSensorPatientMetricsByTimeRangeParams) ([]SensorPatientMetric, error) {
	rows, err := q.db.QueryContext(ctx, ListSensorPatientMetricsByTimeRange,
		arg.SensorID,
		arg.PatientID,
		arg.CreatedAt,
		arg.CreatedAt_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SensorPatientMetric{}
	for rows.Next() {
		var i SensorPatientMetric
		if err := rows.Scan(
			&i.SensorID,
			&i.PatientID,
			&i.MetricID,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
