// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sensors.sql

package repo

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const CountSensors = `-- name: CountSensors :one
SELECT COUNT(*) FROM sensors
`

func (q *Queries) CountSensors(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountSensors)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateSensor = `-- name: CreateSensor :exec
INSERT INTO sensors (
    sensor_id,
    name,
    status,
    enum_name,
    created_at
) VALUES ($1, $2, $3, $4, $5)
`

type CreateSensorParams struct {
	SensorID  uuid.UUID `db:"sensor_id"`
	Name      string    `db:"name"`
	Status    string    `db:"status"`
	EnumName  string    `db:"enum_name"`
	CreatedAt time.Time `db:"created_at"`
}

// SQL constants for mutations (used in repository)
func (q *Queries) CreateSensor(ctx context.Context, arg CreateSensorParams) error {
	_, err := q.db.ExecContext(ctx, CreateSensor,
		arg.SensorID,
		arg.Name,
		arg.Status,
		arg.EnumName,
		arg.CreatedAt,
	)
	return err
}

const DeleteSensor = `-- name: DeleteSensor :exec
DELETE FROM sensors
WHERE sensor_id = $1
`

func (q *Queries) DeleteSensor(ctx context.Context, sensorID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, DeleteSensor, sensorID)
	return err
}

const GetSensor = `-- name: GetSensor :one
SELECT sensor_id, name, status, enum_name, updated_at, created_at
FROM sensors
WHERE sensor_id = $1
LIMIT 1
`

type GetSensorRow struct {
	SensorID  uuid.UUID    `db:"sensor_id"`
	Name      string       `db:"name"`
	Status    string       `db:"status"`
	EnumName  string       `db:"enum_name"`
	UpdatedAt sql.NullTime `db:"updated_at"`
	CreatedAt time.Time    `db:"created_at"`
}

func (q *Queries) GetSensor(ctx context.Context, sensorID uuid.UUID) (GetSensorRow, error) {
	row := q.db.QueryRowContext(ctx, GetSensor, sensorID)
	var i GetSensorRow
	err := row.Scan(
		&i.SensorID,
		&i.Name,
		&i.Status,
		&i.EnumName,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const ListSensors = `-- name: ListSensors :many
SELECT sensor_id, name, status, enum_name, updated_at, created_at
FROM sensors
ORDER BY created_at DESC
`

type ListSensorsRow struct {
	SensorID  uuid.UUID    `db:"sensor_id"`
	Name      string       `db:"name"`
	Status    string       `db:"status"`
	EnumName  string       `db:"enum_name"`
	UpdatedAt sql.NullTime `db:"updated_at"`
	CreatedAt time.Time    `db:"created_at"`
}

func (q *Queries) ListSensors(ctx context.Context) ([]ListSensorsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListSensors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSensorsRow{}
	for rows.Next() {
		var i ListSensorsRow
		if err := rows.Scan(
			&i.SensorID,
			&i.Name,
			&i.Status,
			&i.EnumName,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListSensorsByStatus = `-- name: ListSensorsByStatus :many
SELECT sensor_id, name, status, enum_name, updated_at, created_at
FROM sensors
WHERE status = $1
ORDER BY created_at DESC
`

type ListSensorsByStatusRow struct {
	SensorID  uuid.UUID    `db:"sensor_id"`
	Name      string       `db:"name"`
	Status    string       `db:"status"`
	EnumName  string       `db:"enum_name"`
	UpdatedAt sql.NullTime `db:"updated_at"`
	CreatedAt time.Time    `db:"created_at"`
}

func (q *Queries) ListSensorsByStatus(ctx context.Context, status string) ([]ListSensorsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, ListSensorsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSensorsByStatusRow{}
	for rows.Next() {
		var i ListSensorsByStatusRow
		if err := rows.Scan(
			&i.SensorID,
			&i.Name,
			&i.Status,
			&i.EnumName,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateSensor = `-- name: UpdateSensor :exec
UPDATE sensors
SET
    name = $2,
    status = $3,
    enum_name = $4,
    updated_at = $5
WHERE sensor_id = $1
`

type UpdateSensorParams struct {
	SensorID  uuid.UUID    `db:"sensor_id"`
	Name      string       `db:"name"`
	Status    string       `db:"status"`
	EnumName  string       `db:"enum_name"`
	UpdatedAt sql.NullTime `db:"updated_at"`
}

func (q *Queries) UpdateSensor(ctx context.Context, arg UpdateSensorParams) error {
	_, err := q.db.ExecContext(ctx, UpdateSensor,
		arg.SensorID,
		arg.Name,
		arg.Status,
		arg.EnumName,
		arg.UpdatedAt,
	)
	return err
}
