// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sensors.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const CountSensors = `-- name: CountSensors :one
SELECT COUNT(*) FROM sensors
`

func (q *Queries) CountSensors(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountSensors)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateSensor = `-- name: CreateSensor :exec
INSERT INTO sensors (
    sensor_id,
    name,
    code,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5)
`

type CreateSensorParams struct {
	SensorID  uuid.UUID `db:"sensor_id"`
	Name      string    `db:"name"`
	Code      string    `db:"code"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

// SQL constants for mutations (used in repository)
func (q *Queries) CreateSensor(ctx context.Context, arg CreateSensorParams) error {
	_, err := q.db.ExecContext(ctx, CreateSensor,
		arg.SensorID,
		arg.Name,
		arg.Code,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const DeleteSensor = `-- name: DeleteSensor :exec
DELETE FROM sensors
WHERE sensor_id = $1
`

func (q *Queries) DeleteSensor(ctx context.Context, sensorID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, DeleteSensor, sensorID)
	return err
}

const GetSensor = `-- name: GetSensor :one
SELECT sensor_id, name, code, created_at, updated_at
FROM sensors
WHERE sensor_id = $1
LIMIT 1
`

func (q *Queries) GetSensor(ctx context.Context, sensorID uuid.UUID) (Sensor, error) {
	row := q.db.QueryRowContext(ctx, GetSensor, sensorID)
	var i Sensor
	err := row.Scan(
		&i.SensorID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetSensorByCode = `-- name: GetSensorByCode :one
SELECT sensor_id, name, code, created_at, updated_at
FROM sensors
WHERE code = $1
LIMIT 1
`

func (q *Queries) GetSensorByCode(ctx context.Context, code string) (Sensor, error) {
	row := q.db.QueryRowContext(ctx, GetSensorByCode, code)
	var i Sensor
	err := row.Scan(
		&i.SensorID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListSensors = `-- name: ListSensors :many
SELECT sensor_id, name, code, created_at, updated_at
FROM sensors
ORDER BY created_at DESC
`

func (q *Queries) ListSensors(ctx context.Context) ([]Sensor, error) {
	rows, err := q.db.QueryContext(ctx, ListSensors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sensor{}
	for rows.Next() {
		var i Sensor
		if err := rows.Scan(
			&i.SensorID,
			&i.Name,
			&i.Code,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateSensor = `-- name: UpdateSensor :exec
UPDATE sensors
SET
    name = $2,
    code = $3,
    updated_at = $4
WHERE sensor_id = $1
`

type UpdateSensorParams struct {
	SensorID  uuid.UUID `db:"sensor_id"`
	Name      string    `db:"name"`
	Code      string    `db:"code"`
	UpdatedAt time.Time `db:"updated_at"`
}

func (q *Queries) UpdateSensor(ctx context.Context, arg UpdateSensorParams) error {
	_, err := q.db.ExecContext(ctx, UpdateSensor,
		arg.SensorID,
		arg.Name,
		arg.Code,
		arg.UpdatedAt,
	)
	return err
}
